movie_theater/urls.py
from django.contrib import admin
from django.urls import path
from app import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("movie/<id>/tickets/new", views.NewTicket.as_view(), name="new_ticket"),
    path("ticket/<id>", views.ticket_detail, name="ticket_detail"),
]

app/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.TextField()
    rating = models.TextField()
    genre = models.TextField()
    runtime = models.TextField()


class Showing(models.Model):
    id = models.AutoField(primary_key=True)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    showtime = models.TimeField()


class Ticket(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.TextField()
    purchased_at = models.DateTimeField(auto_now=True)
    showing = models.ForeignKey(Showing, on_delete=models.PROTECT)

app/forms.py
from django import forms

class NewTicketForm(forms.Form):
    name = forms.CharField()
    showing_id = forms.IntegerField()

app/views.py
from django.shortcuts import render, redirect
from app.models import Movie, Ticket, Showing
from app.forms import NewTicketForm
from django.views import View

# Create your views here.
def home(request):
    movies = Movie.objects.all()
    return render(request, "home.html", {"movies": movies})


class NewTicket(View):
    def get(self, request, id):
        movie = Movie.objects.get(id=id)
        form = NewTicketForm()
        return render(request, "new_ticket.html", {"movie": movie, "form": form})

    def post(self, request, id):
        form = NewTicketForm(request.POST)
        if form.is_valid():
            show_id = request.POST["showing_id"]
            showing = Showing.objects.get(id=show_id)
            ticket = Ticket.objects.create(
                name=request.POST["name"], 
                showing=showing
            )
            return redirect("ticket_detail", ticket.id)
        else:
            movie = Movie.objects.get(id=id)
            form = NewTicketForm()
            return render(request, "new_ticket.html", {"movie": movie, "form": form})


def ticket_detail(request, id):
    ticket = Ticket.objects.get(id=id)
    return render(request, "ticket_detail.html", {"ticket": ticket})

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Movie Theater</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% block extra_css %}
    {% endblock extra_css %}
</head>
<body class="container p-5">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.level_tag }}">
                {{ message.message }}
            </div>
        {% endfor %}
    {% endif %}
    {% block content %}
    {% endblock content %}
</body>
</html>

app/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock extra_css %}
{% block content %}
<h1>Movies</h1>
<ul>
{% for movie in movies %}
<li class="card mb-5">
    <div class="card-body">
        <h2 class="card-title">{{ movie.title }}</h2>
        <dl>
            <dt>Rating</dt>
            <dd>{{ movie.rating }}</dd>
            <dt>Runtime</dt>
            <dd>{{ movie.runtime }}</dd>
            <dt>Genre</dt>
            <dd>{{ movie.genre }}</dd>
            <dt>Showings</dt>
            <dd>
                <ol class="showings">
                    {% for showing in movie.showing_set.all %}
                    <li class="showing">
                        <p class="showing__showtime">{{ showing.showtime }}</p>
                    </li>
                    {% endfor %}
                </ol>
            </dd>
            <a href="{% url 'new_ticket' movie.id %}"><button class="btn btn-primary">Buy Ticket</button></a>
        </dl>
    </div>
</li>
{% endfor %}
</ul>
{% endblock content %}

app/templates/new_ticket.html
{% extends 'base.html' %}
{% block content %}
<h1>Buy a ticket for {{ movie.title }}</h1>
<form action="{% url 'new_ticket' movie.id %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="name">Name:</label>
        <input type="text" name="name" id="name" class="form-control" required>
    </div>
    <div class="form-group">
        <label for="showing_id">Showtime</label>
        <select name="showing_id" id="showing_id" class="form-control" required>
            {% for showing in movie.showing_set.all %}
            <option value="{{ showing.id }}">{{ showing.showtime }}</option>
            {% endfor %}
        </select>    
    </div>
    {{ form.errors }}
    <button class="btn btn-primary">Buy Ticket</button>
</form>
{% endblock content %}

app/templates/ticket_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="card">
    <div class="card-body">
        <h1 class="card-title">Ticket #{{ ticket.id }}</h1>
        <dl class="card-text">
            <dt>For</dt>
            <dd>{{ ticket.name }}</dd>
            <dt>Movie</dt>
            <dd>{{ ticket.showing.movie.title }}</dd>
            <dt>Showtime</dt>
            <dd>{{ ticket.showing.showtime }}</dd>
            <dt>Rating</dt>
            <dd>{{ ticket.showing.movie.rating }}</dd>
            <dt>Runtime</dt>
            <dd>{{ ticket.showing.movie.runtime }}</dd>
            <dt>Genre</dt>
            <dd>{{ ticket.showing.movie.genre }}</dd>
            <dt>Purchased At</dt>
            <dd>{{ ticket.purchased_at }}</dd>
        </dl>
        <p class="text-right">Go back <a href="{% url 'home' %}">home</a></p>
    </div>
</div>
{% endblock content %}